openapi: 3.1.0
info:
  version: 1.0.0
  title: Auth-Contact-App
  description: API документація для застосунку авторизації та керування контактами.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
  - name: Contacts
    description: Операції з контактами
  - name: Auth
    description: Операції авторизації

servers:
  - url: https://contact-auth-swagger-app.onrender.com

security:
  - bearerAuth: []

paths:
  /contacts:
    get:
      $ref: ./swagger/paths/contacts/get.yaml
    post:
      $ref: ./swagger/paths/contacts/post.yaml

  /contacts/{id}:
    get:
      $ref: ./swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ./swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ./swagger/paths/contacts/{id}/delete.yaml

  /auth/login:
    post:
      $ref: ./swagger/paths/auth/login/post.yaml

  /auth/register:
    post:
      $ref: ./swagger/paths/auth/register/post.yaml

  /auth/refresh:
    post:
      $ref: ./swagger/paths/auth/refresh/post.yaml

  /auth/logout:
    post:
      $ref: ./swagger/paths/auth/logout/post.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
